apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app 
spec:
  selector:
    app: java-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer