apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app 
spec:
  selector:
    app: java-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
      - http:
         paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-app-service
                port:
                  number: 8080